# **Proyecto Matematicas Discretas II - Uso del RSA (Rivest - Shamir - Adleman)**
**Universidad Nacional de Colombia**
<br/>
Por:
>**Juan Felipe Rojas Cendales**
<br/>
>**Victor Alfredo Barragan Paez**

#### **Introducción**
- Deberá incluir una descripción del problema a resolver, desde el problema más general hasta el problema especifico a abordar.
- Estado del arte, deberá incluir un estado del arte pequeño sobre como se ha abordado este problema antes.

> En el transcurso de la historia de la humanidad existe un factor común y constante que ha brindado todo tipo de ventajas sobre quienes carecen de ella. Indiscutiblemente la **información** juega un papel fundamental en la toma de decisiones que definen los rumbos del hombre, es por esto que se considera como un recurso de sumo valor y el interés de protegerla, conservarla y comunicarla supone un verdadero reto desde el inicio de las primeras civilizaciones hasta nuestros tiempos. 
En general, nuestro objetivo es hacer uso de las matemáticas para preservar la información que buscamos esconder o proteger. Imaginemos por un momento una situación específica donde se busca comunicar un mensaje confidencial a una persona que se encuentra a una distancia considerable, podríamos probar múltiples métodos para realizar el envío pero todas serian igual de inseguras e ineficientes para ocultar el contenido del mensaje ¿Cómo podríamos cumplir con este propósito? Con el paso de los años se han creado diferentes métodos, trucos o **algoritmos matemáticos** que buscan solucionar este tipo de problema y probablemente el más popular en la actualidad es el algoritmo  **RSA**.


> El uso de la criptografía para ocultar información tiene sus inicios en el siglo V a.c. hace 2500 años con la “Escitala”, sin embargo, estos primeros métodos eran fácilmente reversibles. Con el pasar de los años se iban ideando métodos mas elaborados e ingeniosos como el método Cesar, sustitución polialfabética de León Battista Alberti o los numerosos estudios que se han hecho sobre el tema, pero probablemente donde mas se han evidenciado los atributos de la criptografía es en las guerras mundiales con el cifrado ADFGVX (primera guerra mundial) o la máquina Enigma (Segunda Guerra mundial). Luego de la segunda guerra mundial , la criptografía tuvo un desarrollo teórico importante y junto al avance tecnológico , se entra a una nueva era criptográfica la cual nos ha permitido hacer uso de las firmas digitales.
Históricamente el algoritmo RSA descrito en 1977, llega en esa nueva era criptográfica gracias a sus inventores Ron Rivest , Adi Shamir y Leonard Adleman que inspirados por Whitfield Diffie y Martin Hellman , buscaban crear un algoritmo asimétrico capaz de cifrar y autenticar. Básicamente el algoritmo RSA basa su cifrado en la dificultad practica de factorizar el producto de dos números primos grandes.


#### **Materiales y métodos**


1. Deberá incluir la descripción de los datos utilizados (si los hay).

Nuestro set de datos consta de diferentes frases , palabras u oraciones. Estas pasaran por una funcion que "traduce" cada caracter a su respectivo codigo ASCII en un arreglo unidimensional.<br>
De igual manera, haremos uso de numeros primos con el fin de generar las claves necesarias para el funcionamiento del algoritmo.

<img src="https://drive.google.com/uc?export=view&id=1AdHD2jj-b3Jxvp-cAR3UjDinSWBVJv0b" />

In [ ]:
def convertirStringASCII(s):
  return [ord(c) for c in s]
print(convertirStringASCII("Matemáticas Discretas"))

[77, 97, 116, 101, 109, 225, 116, 105, 99, 97, 115, 32, 68, 105, 115, 99, 114, 101, 116, 97, 115]


2. Descripción matemática de los métodos. Se deberá explicar cuales son los fundamentos matemáticos de los algoritmos y/o métodos utilizados. En todos los casos se espera una justificación matemática de los métodos utilizados.


El algoritmo RSA basa su fortaleza en la dificultad de factorizar un numero compuesto muy grande (mayor a 1.000 bits), producto de multiplicar dos primos tambien muy grandes(Mayor a 500 bits).<br>
El algoritmo de cifrado RSA consta basicamente de 3 fases:<br>
(1). Generacion de claves publicas y privadas.<br>
(2). Cifrado del contenido.<br>
(3). Descifrado del contenido.<br>
Para cada una de estas fases es necesario tener una apropiada fundamentacion matematica, por lo tanto, vamos a especificar los fundamentos necesarios para cada paso.<br>

**Generacion de claves publicas y privadas**<br>
En esta primera fase generamos las llaves necesarias para cifrar y descifrar el contenido que deseemos. Es importante tener en cuenta que este proceso matematico sirve unicamente para valores numericos, entonces, si queremos cifrar mensajes debemos encontrar su respectiva traduccion numerica.<br>
Como fundamentos para este paso debemos conocer:<br>

 - **Funcion $\phi$ de Euler:** <br>
 si  $n \in \mathbb{Z^+}$, se define $\phi(n)$ como el numero de enteros positivos menor o iguales a n y coprimos con n:<br>
 $$\phi(n) = |\{ m \in \mathbb{Z^+} \ ; \ m<n \ \wedge mcd(m, n)= 1 \}|$$
 - **Propiedad de la funcion $\phi$ de Euler:** <br>
  Si $n$ y $m$ son primos entre sí, entonces: $$\phi(nm)= \phi(n) \phi(m)$$
 - **Por definicion si n es primo, entonces:** $$\phi (n) = n-1$$
 - **Congruencias**<br/>
 Sea n un entero positivo, los enteros a y b son congruentes mod n si tienen el mismo residuo una vez se divida por n.
 $$a \equiv b (\ mod n) $$<br/>
 - **Maximo comun divisor (M.C.D)**<br/>
 - **El polinomio de J Brox** <br/>
 No existe un polinomio $P(n)$ que para todos los valores de $n$ el resultado sea un número primo. Sin embargo, existen polinomios que para un rango de valores de $n$ generan estos números. Euler, Legendre, entre otros, son algunos polinomios famosos que generan números primos. Es posible demostrar que solo una función constante es admitida como polinomio capaz de entregar u valor primo para $n$ valores, se puede encontrar esta demostración en la referencia #4. <br/>**El polinomio de J Brox** es el polinomio con rango de valores $n$ [0-57], 57 valores diferentes de números primos. $$P(n) = 6n^2 -342n +4903$$ 
 - **Algoritmo extendido de Euclides ( Identidad de Bezout)**<br/>
 si a y b son enteros, ambos diferentes de 0, y sea d el M.C.D entre a y b. Entonces existen enteros v y w tales que:
 $$d=a v  + bw$$

**Cifrado y Descifrado**
En estas 2 fases del algoritmo, transformamos el valor numerico cifrandolo con la llave publica y desciframos el valor con la llave privada. Para esto es necesario tener encuenta las siguientes formulas:
$$ C \equiv M^e (\ mod \ n\ )$$
$$ M \equiv C^d (\ mod \ n\ )$$
Donde $C$ es el valor cifrado, $M$ es valor sin cifrar , $e$ es clave publica, $d$ es la clave privada y $n$ es el producto de dos numeros primos.

3. Algoritmos se deberán describir de forma clara el algoritmo principal utilizado.


El algoritmo RSA funciona de la siguiente manera:<br>
**Fase de generacion de claves publicas y privadas**
>1. Generamos aleatoriamente dos numeros primos grandes utilizando el polinomio de J Brox y valores de n entre 10 y 57 (mayores a 500 bits), a los que llamaremos $p$ y $q$. 
2. Calculamos el valor de $n$ multiplicando $p$ y $q$:
$$n=p*q$$
3.Usamos la funcion $\phi$ de Euler calculando:
 $$\phi (n) = (p-1)(q-1)$$
 ya que $n=p*q$ entonces $\phi (n)$ es igual a $\phi (pq)$.
4. Calcular un numero natural $e$ de manera que $$M.C.D(e,\phi (n))=1$$
es decir que e debe ser coprimo de $\phi (n)$. Con esto obtendriamos $e$ que es la **clave publica**.
5. Calcular mediante el algoritmo extendido de Euclides (identidad de Bezout) un numero $d$ entero, tal que:
$$ed\ (mod \ \phi (n)\ ) =1$$ 
Con el valor que encontremos de $d$ obtendriamos la clave privada.

**Fase de cifrado y descifrado**
> 1. Ciframos el valor mediante la funcion de cifrado:
$$ C \equiv M^e (\ mod \ n\ )$$
2. Desciframos el valor mediante la funcion de descifrado:
$$ M \equiv C^d (\ mod \ n\ )$$ <br/> 
> Sea $ C \equiv M^e (\ mod \ n\ )$ la función de cifrado que asigna a cada letra un entero para formar un mensaje como bloque de enteros. La función de descifrado busca un inverso $d$ para la llave pública $e$ mod $(p-1)(q-1)$.<br/>
> Sea $ C^d = (M^e)^d$  = M^(1+k(p-1)(q-1))<br/> 
> Luego $M^p M^-1 \equiv ( 1 \mod \ p)$ y $M^q M^-1 \equiv ( 1\mod \ q)$ <br/>
> Reescribimos  M^(1+k(p-1)(q-1)) <br/> 
> $M((M^p M^-1)^k)^(q-1) \equiv M \mod p$ <br/>
>  $M((M^q M^-1)^k)^(p-1) \equiv M \mod q$ <br/>
> $C ^ d \equiv M \mod p$ <br/>
> $C ^ d \equiv M \mod q$ <br/>
> Por tanto $C ^ d \equiv M \mod pq \equiv M \mod n$


4. Configuración experimental. Se deberán realizar experimentos para estudiar aspectos computacionales de la solución propuesta, esta sección describirá dichos aspectos.

**Experimento #1**<br>
**Fase de generacion de claves publicas y privadas**<br>


> Definimos $p$ y $q$:<br>
$p=839$ , $q=947$<br>

> Definimos $n$ como el producto entre $p$ y $q$:<br>
$n=839 * 947 = 794533$<br>

> Calculamos $\phi (n)$:<br>
$\phi (n)=(p-1)*(q-1)=838*946=792748$<br>

> Debemos elegir nuestra llave publica ($e$) de tal modo que  1 < e < $\phi (n)$  y para asegurarnos de que exista el inverso multiplicativo y por lo tanto la existencia de la clave privada inversa de esa clave publica, debemos asegurarnos que :<br>
$mcd(e,\phi(n)) =1 $<br>
En este caso, vamos a escoger:
$e=41$

> Calculamos nuestra llave privada usando el algoritmo extendido de Euclides.<br>
$ed \equiv 1 \ mod (\phi(n)) $<br>
Este tambien puede calcularse como:<br>
$d= \frac{(Y \ . \ \phi(n)) +1}e{}$ para Y = 1,2,3... hasta encontrar un d entero.<br>
Sin embargo nos apoyamos de Python para realizar este calculo:

In [ ]:
def obtenerClavePrivada(e,phi_n):
  y=1
  while ((( y * phi_n )+1) % e != 0):
    y=y+1
  return (( y * phi_n )+1)/e 
print(obtenerClavePrivada(41, 792748))

425377.0


> obteniendo el valor de nuestra clave privada $d=425377$ 

>Entonces la llave publica es (41,794533) y la privada es (425377,794533)

**Fase de cifrado y descifrado**
Para esta fase, podemos cifrar una afirmacion , oracion o mensaje si lo transformamos a su equivalente numerico (ASCII).
>convertir String a Ascii:

In [ ]:
def convertirStringASCII(s):
  return [ord(c) for c in s]
print(convertirStringASCII("Matemáticas Discretas"))

[77, 97, 116, 101, 109, 225, 116, 105, 99, 97, 115, 32, 68, 105, 115, 99, 114, 101, 116, 97, 115]


> Ciframos el mensaje con la llave publica aplicando la funcion:<br>
$ C \equiv M^e (\ mod \ n\ )$


In [ ]:
mensaje = [77, 97, 116, 101, 109, 225, 116, 105, 99, 97, 115, 32, 68, 105, 115, 99, 114, 101, 116, 97, 115]
cifrado = []

def cifrar(e,n,m):
  return pow(m,e,n)

for letra in mensaje:
  cifrado.append(cifrar(41,794533,letra))

print("El mensaje cifrado es: ")
print(cifrado)

El mensaje cifrado es: 
[381623, 444759, 351, 312228, 62654, 94995, 351, 652890, 106932, 444759, 759207, 313654, 207559, 652890, 759207, 106932, 454988, 312228, 351, 444759, 759207]


> Por ultimo, desciframos el mensaje con la llave privada y aplicando la funcion: <br>
$M \equiv C^d (\ mod \ n\ )$

In [ ]:
cifrado = [381623, 444759, 351, 312228, 62654, 94995, 351, 652890, 106932, 444759, 759207, 313654, 207559, 652890, 759207, 106932, 454988, 312228, 351, 444759, 759207]

descifrado = []

def descifrar(d,n,c):
  return pow(c,d,n)

for letra in cifrado:
  descifrado.append(descifrar(425377,794533,letra))

print("El mensaje cifrado es: ")
print(descifrado)

El mensaje cifrado es: 
[77, 97, 116, 101, 109, 225, 116, 105, 99, 97, 115, 32, 68, 105, 115, 99, 114, 101, 116, 97, 115]


> Convertimos el arreglo en string y obtenemos


In [ ]:
descifrado= [77, 97, 116, 101, 109, 225, 116, 105, 99, 97, 115, 32, 68, 105, 115, 99, 114, 101, 116, 97, 115]
def convertirASCIIString(s):
  return ''.join(chr(c) for c in s)
print(convertirASCIIString(descifrado))

Matemáticas Discretas


**Experimento #2**<br>
**Fase de generacion de claves publicas y privadas**<br>

> Generamos utilizando el polinomio de J Brox dos números primos:

In [ ]:
import random
def jbrox(): 
  n = random.randint(45,57)
  return 6*(n)**2 - (342*n) + 4903
print("p:",jbrox())
print("q:",jbrox())

p: 3343
q: 3931



> Definimos $p$ y $q$:<br>
$p=1867$ , $q=2311$<br>

> Definimos $n$ como el producto entre $p$ y $q$:<br>
$n=1867 * 2311 = 4314637$<br>

> Calculamos $\phi (n)$:<br>
$\phi (n)=(p-1)*(q-1)=1866*2310= 4310460$<br>

> Debemos elegir nuestra llave publica ($e$) de tal modo que  1 < e < $\phi (n)$  y para asegurarnos de que exista el inverso multiplicativo y por lo tanto la existencia de la clave privada inversa de esa clave publica, debemos asegurarnos que :<br>
$mcd(e,\phi(n)) =1 $<br>
En este caso, vamos a escoger:
$e=65537$ Cuarto número de Fermat

> Calculamos nuestra llave privada usando el algoritmo extendido de Euclides.<br>
$ed \equiv 1 \ mod (\phi(n)) $<br>
Este tambien puede calcularse como:<br>
$d= \frac{(Y \ . \ \phi(n)) +1}e{}$ para Y = 1,2,3... hasta encontrar un d entero.<br>
Sin embargo nos apoyamos de Python para realizar este calculo:

In [ ]:
def obtenerClavePrivada(e,phi_n):
  y=1
  while ((( y * phi_n )+1) % e != 0):
    y=y+1
  return (( y * phi_n )+1)/e 
print(obtenerClavePrivada(65537, 4310460))

873773.0


> obteniendo el valor de nuestra clave privada $d=873773$ 

>Entonces la llave publica es (65537,4314637) y la privada es (873773,4314637)

**Fase de cifrado y descifrado**
Para esta fase, podemos cifrar una afirmacion , oracion o mensaje si lo transformamos a su equivalente numerico (ASCII).
>convertir String a Ascii:

In [ ]:
def convertirStringASCII(s):
  return [ord(c) for c in s]
print(convertirStringASCII("Polinomio de J Brox"))

[80, 111, 108, 105, 110, 111, 109, 105, 111, 32, 100, 101, 32, 74, 32, 66, 114, 111, 120]


> Ciframos el mensaje con la llave publica aplicando la funcion:<br>
$ C \equiv M^e (\ mod \ n\ )$


In [ ]:
mensaje = [80, 111, 108, 105, 110, 111, 109, 105, 111, 32, 100, 101, 32, 74, 32, 66, 114, 111, 120]
cifrado = []

def cifrar(e,n,m):
  return pow(m,e,n)

for letra in mensaje:
  cifrado.append(cifrar(65537,4314637,letra))

print("El mensaje cifrado es: ")
print(cifrado)

El mensaje cifrado es: 
[1915500, 1413363, 286617, 1709927, 1802348, 1413363, 471942, 1709927, 1413363, 96819, 497583, 3556802, 96819, 2379598, 96819, 3845828, 4173536, 1413363, 3042246]


> Por ultimo, desciframos el mensaje con la llave privada y aplicando la funcion: <br>
$M \equiv C^d (\ mod \ n\ )$

In [ ]:
cifrado = [1915500, 1413363, 286617, 1709927, 1802348, 1413363, 471942, 1709927, 1413363, 96819, 497583, 3556802, 96819, 2379598, 96819, 3845828, 4173536, 1413363, 3042246]
descifrado = []

def descifrar(d,n,c):
  return pow(c,d,n)

for letra in cifrado:
  descifrado.append(descifrar(873773,4314637,letra))

print("El mensaje descifrado ASCII es: ")
print(descifrado)

El mensaje descifrado ASCII es: 
[80, 111, 108, 105, 110, 111, 109, 105, 111, 32, 100, 101, 32, 74, 32, 66, 114, 111, 120]


> Convertimos el arreglo en string y obtenemos


In [ ]:
descifrado= [80, 111, 108, 105, 110, 111, 109, 105, 111, 32, 100, 101, 32, 74, 32, 66, 114, 111, 120]
def convertirASCIIString(s):
  return ''.join(chr(c) for c in s)
print(convertirASCIIString(descifrado))

Polinomio de J Brox


#### **Resultados**
- Deberá reportar los resultados de los experimentos realizados. Para esto se deberán incluir bloques de código que permitan reproducir TODOS los resultados reportados.

> En la anterior sección realizamos un análisis paso por paso del algoritmo RSA presentando bloques de código sin relación que ejecutaban funciones necesarias o partes del algoritmo. En esta sección presentaremos los resultados con una situación cotidiana (mensajero, receptor) ejemplificada en un programa. <br/> 
> Suponga que Alejandra quiere enviar un mensaje confidencial a Ramiro, para esto ella busca la clave pública de Ramiro y encripta su mensaje con esta clave. Ramiro conoce RSA y sabe que Alejandra debe tener acceso a su clave pública y su valor $n$. <br/> 
Alicia encuentra los valores $n$ = 4314637 y $e$ = 65537 y procede a encriptar su mensaje. <br/> 
Puede reemplazar el mensaje que envia Alicia y comprobar en el segundo bloque de codígo  el resultado solo reemplazado el mensajeRecibidoPorRamiro por el arreglo salida del primer bloque de código.

In [ ]:
mensajeAlicia = "Los computadores cuanticos se acercan" 
def convertirStringASCII(s):
  return [ord(c) for c in s]; 
mensajeAliciaASCII = convertirStringASCII(mensajeAlicia)
cifrado = []

def cifrar(e,n,m):
  return pow(m,e,n)

for letra in mensajeAliciaASCII:
  cifrado.append(cifrar(65537,4314637,letra))
print(cifrado)

[1694244, 1413363, 2837536, 96819, 1131796, 1413363, 471942, 1286669, 2357225, 157864, 1525963, 497583, 1413363, 4173536, 3556802, 2837536, 96819, 1131796, 2357225, 1525963, 1802348, 157864, 1709927, 1131796, 1413363, 2837536, 96819, 2837536, 3556802, 96819, 1525963, 1131796, 3556802, 4173536, 1131796, 1525963, 1802348]


> El mensaje de Alicia viaja convertido en ese arreglo de enteros y es recibido por Ramiro que utilizará su clave privada $d$ para descifrarlo. 

In [ ]:
mensajeRecibidoPorRamiro = [1694244, 1413363, 2837536, 96819, 1131796, 1413363, 471942, 1286669, 2357225, 157864, 1525963, 497583, 1413363, 4173536, 3556802, 2837536, 96819, 1131796, 2357225, 1525963, 1802348, 157864, 1709927, 1131796, 1413363, 2837536, 96819, 2837536, 3556802, 96819, 1525963, 1131796, 3556802, 4173536, 1131796, 1525963, 1802348]
descifrado = []

def descifrar(d,n,c):
  return pow(c,d,n)

for letra in mensajeRecibidoPorRamiro:
  descifrado.append(descifrar(873773,4314637,letra))
def convertirASCIIString(s):
  return ''.join(chr(c) for c in s)
print(convertirASCIIString(descifrado))

Los computadores cuanticos se acercan


> De esta manera comprobamos los resultados obtenidos en la sección anterior con un ejemplo más práctico y entendible en donde Ramiro recibió su mensaje teniendo en cuenta la privacidad total de su clave $d$

 **Conclusiones**



- Se deberán redactar conclusiones relacionados con la solución propuesta.




*   RSA es la manera más común, eficaz y segura para mantener la privacidad de la información, su éxito de fundamenta en la teoría de números y la gran incógnita que se tiene con la factorización de números primos grandes.
*   En RSA se deben mantener en secreto los números primos $p$,$q$ y la clave para descifrar $d$. Se deben hacer públicos los valores de $n$ y la clave pública para encriptar $e$. 
* La integridad de este algoritmo depende de la eficiencia de los ordenadores para factorizar $n$, con el aumento de rendimiento en los ordenadores se debe aumentar el valor de $n$ y la manera de generar $p$ y $q$ más grandes.
* El problema RSA como es conocido en criptografía fundamenta su dificultad en encontrar una clave privada dado solo la clave pública y es la base de todo un sistema de seguridad aplicado en sistemas de Internet of Things, banca, entre otros.  



#### **Referencias**
- Se deberán incluir referencias que soporten el trabajo. Las referencias deberán ser de calidad: Artículos de revista, Libros, Proceedings, Capítulos de libro.

- Diaz, E.H.D.R(2005). EL CRIPTOSISTEMA RSA. Editorial Ra-Ma.
- Muñoz, A.M.,& Aguirre, J.R.(2019). Cifrado de las comunicaciones digitales(Vol.1).OxWORD.
- Preneel. B.,Paar,C.,& Pelzl, J. (2014). Understanding Cryptography: A Textbook for Students and Practitioners (2010 ed.) Springer.
-Funciones que generan números primos. (2019, 20 agosto). Lo fascinante de la teoría de números. https://sselbergg.wordpress.com/2013/11/04/funciones-que-generan-numeros-primos/